// websocket端口
export const WEBSOCKET_PORT = 19002
// // 流量统计属性信息对象
// export const FLOW_PROPERTY_MAP = {
//   people_flow_rate: { text: '行人流量', unit: '' },
//   no_motor_flow_rate: { text: '非机动车流量', unit: '辆/分钟' },
//   small_flow_rate: { text: '小车流量', unit: '辆/分钟' },
//   medium_flow_rate: { text: '中车流量', unit: '辆/分钟' },
//   big_flow_rate: { text: '大车流量', unit: '辆/分钟' },
//   pcu_flow_rate: { text: '标准车当量', unit: '辆/分钟' },
//   time_gap: { text: '车道平均车身时距', unit: '' },
//   avg_cross_line_cost_time: { text: '平均跨线时间', unit: 's' },
//   avg_delay_time: { text: '平均延误时间', unit: 's' },
//   avg_speed: { text: '车道平均速度', unit: 'm/s' },
//   desaturation: { text: '饱和度', unit: '' },
//   flow: { text: '车道经过数量', unit: '辆' },
//   flow_rate: { text: '车道流量', unit: '辆/分钟' },
//   flow_speed: { text: '车流平均速度', unit: 'm/s' },
//   go_through: { text: '通行能力', unit: '' },
//   head_tail: { text: '车道平均首尾距离', unit: 'm' },
//   occupy_space_rate: { text: '车道平均空间占用率', unit: '%' },
//   occupy_time_rate: { text: '车道平均时间占用率', unit: '%' },
//   queue_dist: { text: '车道排队长度', unit: 'm' },
//   queue_lenth: { text: '车道排队数量', unit: '辆' },
//   queue_loc: { text: '车道排队队首队尾位置', unit: '' },
//   speed_85: { text: '85位速度', unit: '' },
//   space_headway: { text: '车道平均车头间距', unit: 'm' },
//   stop_time: { text: '停车次数', unit: '' },
//   time_headway: { text: '车道平均车头时距', unit: 's' },
// }
// 流量统计属性信息数组
export const FLOW_PROPERTY_LIST = [
  { key: 'lane_people_flow_rate', text: '行人流量', unit: '' },
  { key: 'lane_no_motor_flow_rate', text: '非机动车流量', unit: '辆/分钟' },
  { key: 'lane_small_flow_rate', text: '小车流量', unit: '辆/分钟' },
  { key: 'lane_medium_flow_rate', text: '中车流量', unit: '辆/分钟' },
  { key: 'lane_big_flow_rate', text: '大车流量', unit: '辆/分钟' },
  { key: 'lane_pcu_flow_rate', text: '标准车当量', unit: '辆/分钟' },
  { key: 'lane_time_gap', text: '车道平均车身时距', unit: '' },
  { key: 'lane_avg_cross_line_cost_time', text: '平均跨线时间', unit: 's' },
  { key: 'lane_avg_delay_time', text: '平均延误时间', unit: 's' },
  { key: 'lane_avg_speed', text: '车道平均速度', unit: 'm/s' },
  { key: 'lane_desaturation', text: '饱和度', unit: '' },
  { key: 'lane_flow', text: '车道经过数量', unit: '辆' },
  { key: 'lane_flow_rate', text: '车道流量', unit: '辆/分钟' },
  { key: 'lane_flow_speed', text: '车流平均速度', unit: 'm/s' },
  { key: 'lane_go_through', text: '通行能力', unit: '' },
  { key: 'lane_head_tail', text: '车道平均首尾距离', unit: 'm' },
  { key: 'lane_occupy_space_rate', text: '车道平均空间占用率', unit: '%' },
  { key: 'lane_occupy_time_rate', text: '车道平均时间占用率', unit: '%' },
  { key: 'lane_queue_dist', text: '车道排队长度', unit: 'm' },
  { key: 'lane_queue_lenth', text: '车道排队数量', unit: '辆' },
  { key: 'lane_queue_loc', text: '车道排队队首队尾位置', unit: '' },
  { key: 'lane_speed_85', text: '85位速度', unit: '' },
  { key: 'lane_space_headway', text: '车道平均车头间距', unit: 'm' },
  { key: 'lane_stop_time', text: '停车次数', unit: '' },
  { key: 'lane_time_headway', text: '车道平均车头时距', unit: 's' },
]
